unlink("mtcars.json")
unlink("mtcarslist.json")
x <- elastic::connect(port = Sys.getenv("TEST_ES_PORT"))
ins <- names(elastic::alias_get(x))
for (i in ins) invisible(elastic::index_delete(x, index = i, verbose = FALSE))
